#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = u'J.Paul Rinehimer'
SITENAME = u'J.Paul Rinehimer'
SITEURL = '' #Set in publishconf.py

PATH = 'content'

TIMEZONE = 'US/Pacific'

DEFAULT_LANG = u'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
		 ('PyHOGS', 'http://pyhogs.github.io'),)

# Social widget
SOCIAL = (('Github', 'https://github.com/jprine'),)
FEEDS = True
GITHUB_URL = "https://github.com/jprine"

DEFAULT_PAGINATION = False

# Crowsfoot specific addresses
EMAIL_ADDRESS='jprine@apl.uw.edu'
GITHUB_ADDRESS='https://github.com/jprine'
#PROFILE_IMAGE_URL=''  # Add image here
SHOW_ARTICLE_AUTHOR=False

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

# Add README.md to output dir - mainly for Github repo.
STATIC_PATHS = ['README.md', 'images', 'static']


# Custom theme settings
THEME = 'crowsfoot'

# Plugins
#PLUGIN_PATHS = ['pelican-plugins']
#PLUGINS = ['summary', ]

# IPython Notebooks configuration
# This header file is automatically generated by the notebook plugin
#if not os.path.exists('_nb_header.html'):
#    import warnings
#    warnings.warn("_nb_header.html not found. Rerun make html to finalize build.")
#else:
#    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')

#PLUGINS += ['liquid_tags.notebook', 'liquid_tags.literal']
#NOTEBOOK_DIR = '../pyhogs-code/notebooks/'